autoInstallPeers: true

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - prisma
